### ISSUE TITLE
np.float 已被弃用，导致代码兼容性问题

### ISSUE THREAD

**Issue by sheyuew** [NJUPT-MCC/MGCN#1]
### 问题描述:
由于在较新的 numpy 版本中，`np.float` 已被弃用，而在代码中仍然使用了这个已弃用的别名，导致运行时报错。

### 错误信息:
AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the built-in `float`. To avoid this error in existing code, use `float` by itself.

### 解决建议:
将代码中的 `np.float` 替换为 `float` 或 `np.float64` 以确保兼容较新的 numpy 版本。

**Comment by demonph10** [comment]
感谢！
